---

- hosts: master
  become: yes
  vars:
     k8s_mode: "master"
     nfs_exports: [ "/opt/share *(rw,sync,no_root_squash)" ]
     node_arch: "arm"
     pod_network: "weave"
  roles:
     - ansible-role-k8s
     - ansible-role-nfs

- hosts: worker
  become: yes
  vars:
     k8s_mode: "worker"
  roles:
     - ansible-role-k8s
     - ansible-role-k8sHLF
     - ansible-role-nfs

