---

- hosts: master
  become: yes
  vars:
     k8s_mode: "master"
     nfs_exports: [ "/opt/share *(rw,sync,no_root_squash)" ]
     node_arch: "arm"
     pod_network: "weave"
  roles:
     - ansible-role-k8s
     - ansible-role-nfs
     - ansible-role-nodejs

- hosts: worker
  become: yes
  vars:
     k8s_mode: "worker"
  roles:
     - ansible-role-k8s
     - ansible-role-k8sHLF
     - ansible-role-nfs
  tasks:
     - name: create share directory
       file:
          path: /opt/share
          state: directory
     - name: nfs mount /opt/share
       command: mount -o rw,nolock 192.168.31.200:/opt/share /opt/share
       become: yes
    
    
