---

- hosts: master
  become: yes
  vars:
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}=17.03.2~ce-0~ubuntu-xenial"
    docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} xenial {{ docker_apt_release_channel }}"
    # docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
    docker_package_state: present
    docker_users: ['vagrant']
    docker_install_compose: false
  roles:
    - ansible-role-docker
    - ansible-role-nodejs

- hosts: master
  become: yes
  roles:
    - ansible-role-ruby

- hosts: worker
  become: yes
  vars:
    hostname: "{{ inventory_hostname }}"
    home: "/home/pirate"
  tasks:
    - name: Ensure hostname set
      shell: "hostnamectl set-hostname {{ inventory_hostname }}"
      # hostname: name={{ inventory_hostname }}
      when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
    #   register: hostname
    #   tags: hostname

    - name: Ensure hostname init
      shell: "device-init hostname set {{ inventory_hostname }}"

    - name: Ensure hostname init
      shell: "device-init hostname set {{ inventory_hostname }}"
    
    - name: Download Template kube-proxy arm 
      template:
        src: ./device-init.j2
        dest: "/boot/device-init.yaml"
    
    - name: Ensure hostname init
      become: yes
      shell: "device-init -c /boot/device-init.yaml"
    